---
- name: Instalar y configurar PulseAudio en el servidor
  hosts: localhost
  become: yes
  tasks:

    - name: Actualizar paquetes del sistema
      apt:
        update_cache: yes

    - name: Instalar PulseAudio, pavucontrol y pulseaudio-utils
      apt:
        name:
          - pulseaudio
          - pavucontrol
          - pulseaudio-utils
        state: present

    - name: Verificar que PulseAudio esté instalado
      command: which pulseaudio
      register: pulseaudio_installed
      ignore_errors: yes

    - name: Mostrar mensaje de éxito
      debug:
        msg: "✅ PulseAudio ha sido instalado correctamente."
      when: pulseaudio_installed.rc == 0
